- name: install glusterfs-server package
  apt:
   name: glusterfs-server
   state: present
   update_cache: yes
  tags: glusterfs

- name: Connect to Gluster peers.
  shell: "gluster peer probe {{ item }}"
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  failed_when: false
  with_items: groups.worker
  tags: glusterfs,glusterfs_cluster

- name: create gluster volume
  gluster_volume:
    name: '{{ glusterfs_volume_name }}'
    state: present
    bricks: '{{ glusterfs_dir }}'
    replicas: '{{ glusterfs_replicas }}'
    cluster: '{{ groups.worker }}'
    transport: '{{ glusterfs_transport_type }}'
    force: true
  run_once: true
  tags: glusterfs,glusterfs_volume

- name: start gluster volume
  gluster_volume:
    name: '{{ glusterfs_volume_name }}'
    state: started
  tags: glusterfs,glusterfs_volume

- name: create gluster mount point
  file:
    path: '{{ gluster_volume_mountpoint }}'
    state: directory
  tags: glusterfs,glusterfs_volume

- name: mount gluster volume
  mount:
    name: '{{ gluster_volume_mountpoint }}'
    src: "{{ groups.worker[0] }}:{{ glusterfs_volume_name }}"
    fstype: glusterfs
    state: mounted
  tags: glusterfs,glusterfs_volume
