- name: install lvm2 and xfs package
  apt:
    name: 
      - lvm2
      - xfsprogs
    state: present
    update_cache: yes
  tags: glusterfs,lvm,xfs

- name: create glusterfs VG
  lvg:
    vg: '{{ glusterfs_vg_name }}'
    pvs: '/dev/{{ glusterfs_part }}'
    state: present
  tags: glusterfs,lvm

- name: create glusterfs LV
  lvol:
    vg: '{{ glusterfs_vg_name }}'
    lv: '{{ glusterfs_lv_name }}'
    size: 100%FREE
    shrink: false
    state: present
  tags: glusterfs,lvm

- name: format LV with XFS
  filesystem:
    fstype: xfs
    dev: '/dev/{{ glusterfs_vg_name }}/{{ glusterfs_lv_name }}'
  tags: glusterfs,xfs

- name: create /var/lib/glusterfs directory
  file:
    path: '{{ glusterfs_dir }}'
    state: directory
  tags: glusterfs,xfs

- name: mount glusterfs LV
  mount:
    name: '{{ glusterfs_dir }}'
    src: '/dev/{{ glusterfs_vg_name }}/{{ glusterfs_lv_name }}'
    fstype: xfs
    state: mounted
  tags: glusterfs,xfs
  
